import { Open_Sans } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import Navbar from "@/components/primary/Navbar";

// Importa Open Sans
const openSans = Open_Sans({ subsets: ["latin"], variable: "--font-open-sans" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js" defer></script>
        <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap"
          />
      </Head>
      <body className={`bg-black ${openSans.variable}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
